export const techTalkData = [
  {
    id: 1,
    href: 'https://www.youtube.com/watch?v=AT7OZMRtc7s',
    src: 'https://img.youtube.com/vi/AT7OZMRtc7s/mqdefault.jpg',
    title: '할 수 있다고 생각해보는 것',
    presenter: '1기 박우림 • 백엔드 • 동기부여 ',
  },
  {
    id: 2,
    href: 'https://www.youtube.com/watch?v=Jgwrdk60Cj4',
    src: 'https://i.ytimg.com/vi/Jgwrdk60Cj4/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFooTjAP&rs=AOn4CLB9SRaFBizuJrVtfVJwGvIMR7JWug',
    title: 'Prisma',
    presenter: '7기 조영은 • 백엔드 • 테크톡',
  },
  {
    id: 3,
    href: 'https://www.youtube.com/watch?v=KkphWKI1rCw',
    src: 'https://i.ytimg.com/vi/KkphWKI1rCw/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIGUoZTAP&rs=AOn4CLCPUOwg7_o1M6VOgJ3qyvbNB2sp3A',
    title: 'MVC패턴',
    presenter: '7기 김진 • 프론트엔드 • 테크톡',
  },
  {
    id: 4,
    href: 'https://www.youtube.com/watch?v=N4r7PqaamL4',
    src: 'https://i.ytimg.com/vi/N4r7PqaamL4/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFooVTAP&rs=AOn4CLAyK4-yMmW8OElCVl_2_i6MTpa82A',
    title: '네트워크 보안',
    presenter: '7기 김준우 • 백엔드 • 테크톡',
  },
  {
    id: 5,
    href: 'https://www.youtube.com/watch?v=KNusQBEgtGc',
    src: 'https://i.ytimg.com/vi/KNusQBEgtGc/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFwoWTAP&rs=AOn4CLCqz9Ft8rRsOb8uwUW40XB2FneO-Q',
    title: 'TypeScript & Generic',
    presenter: '6기 이재진 • 프론트엔드 • 테크톡',
  },
  {
    id: 7,
    href: 'https://www.youtube.com/watch?v=ubcg-_c5v4k',
    src: 'https://i.ytimg.com/vi/ubcg-_c5v4k/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFooUTAP&rs=AOn4CLC1GDCuUSPx4_vU2d7aId-f2D6uxQ',
    title: '색상',
    presenter: '6기 정효준 • 디자인 • 테크톡',
  },
  {
    id: 8,
    href: 'https://www.youtube.com/watch?v=zeSt7DukgEU',
    src: 'https://i.ytimg.com/vi/zeSt7DukgEU/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFcoUzAP&rs=AOn4CLDTuprA-9bjo-8dieoKvbfS32J9LQ',
    title: '트랜잭션',
    presenter: '6기 정비호 • 백엔드 • 테크톡',
  },
];
