export const techTalkData = [
  {
    id: 1,
    href: 'https://www.youtube.com/watch?v=AT7OZMRtc7s',
    src: 'https://img.youtube.com/vi/AT7OZMRtc7s/mqdefault.jpg',
    title: '할 수 있다고 생각해보는 것',
    presenter: '1기 박우림 • 백엔드 • 동기부여 ',
  },
  {
    id: 2,
    href: 'https://www.youtube.com/watch?v=6MWKNfW1O9U',
    src: 'https://i.ytimg.com/vi/6MWKNfW1O9U/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLD5BgKmA9cR1f9Dn2IITWPnJKtaRA',
    title: '8기 최종 회고',
    presenter: '8기 홍대경 • 백엔드 • 회고',
  },
  {
    id: 3,
    href: 'https://www.youtube.com/watch?v=nOYInRTEzlo',
    src: 'https://i.ytimg.com/vi/nOYInRTEzlo/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGGUgXihOMA8=&rs=AOn4CLDr__dxTeXIIXeZV9zqtZjie42w4Q',
    title: '데이터 정규화 - 이희민',
    presenter: '9기 이희민 • 프론트엔드 • 테크톡',
  },
  {
    id: 4,
    href: 'https://www.youtube.com/watch?v=iNUcR89mOf4',
    src: 'https://i.ytimg.com/vi/iNUcR89mOf4/hqdefault.jpg?sqp=-oaymwEnCNACELwBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCBoGHgBJnD1Xd54T8ldwgyIf2a6Q',
    title: 'DNS',
    presenter: '9기 강승민 • 백엔드 • 테크톡',
  },
  {
    id: 5,
    href: 'https://www.youtube.com/watch?v=Fx7FbO5Pwd0',
    src: 'https://i.ytimg.com/vi/Fx7FbO5Pwd0/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGHIgXyg1MA8=&rs=AOn4CLDVbW6qgIZPfDcM8KHMli3IBitlLg',
    title: 'OSI 7 Layer',
    presenter: '8기 구도윤 • 프론트엔드 • 테크톡',
  },
  {
    id: 6,
    href: 'https://www.youtube.com/watch?v=FzDl5SxEG5Y',
    src: 'https://i.ytimg.com/vi/FzDl5SxEG5Y/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGFIgXyhlMA8=&rs=AOn4CLAPnsLp30C3rKdmfociQ26SseQygA',
    title: 'ERD',
    presenter: '8기 전희나 • 백엔드 • 테크톡',
  },
  {
    id: 7,
    href: 'https://www.youtube.com/watch?v=2X7aUAn_PY4',
    src: 'https://i.ytimg.com/vi/2X7aUAn_PY4/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGD4gWChyMA8=&rs=AOn4CLCHtnrWjYuPi1dFnMAxG8o0fdKS6w',
    title: '객체 지향 프로그래밍',
    presenter: '8기 홍대경 • 백엔드 • 테크톡',
  },
];
